// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.kilo.domain;

import java.lang.String;

privileged aspect MoneyValue_Roo_ToString {
    
    public String MoneyValue.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Amount: ").append(getAmount());
        return sb.toString();
    }
    
}
